### ISSUE TITLE
no matching account found

### ISSUE THREAD

**Issue by muralikodali** [gnojus/nec#1]
output of `nec share Readme.md` is shown below :

```
Error: reading config: no matching account found

```

**Comment by muralikodali** [comment]
`nec ls -r ` showing up shares as below :

```
/Ebooks/DesigningEbooks.mobi  2208  https://my.opendesktop.org/s/xxxxxxxxxxxxxxx
/Uploads/                     2210  https://my.opendesktop.org/s/xxxxxxxxxxxxxxx
/finance/houserent.ods        2219  https://my.opendesktop.org/s/xxxxxxxxxxxxxxx
```

**Comment by gnojus** [comment]
It looks like the directory  containing `Readme.md` (and this file itself) is not synced by the Nextcloud desktop app. Then this is expected behaviour, you can only share files that are synced with the server.

If that's not the case, could you share the full path of `Readme.md` and your `nextcloud.cfg`? (its in `~/.config/Nextcloud` on Linux, `~/Library/Application Support/Nextcloud` on Mac os, and `%appdata%/Nextcloud` on Windows if I'm not mistaken).

I expect `nec ls -r .` will show the same error.

Note that when you don't pass the `path` argument to `nec ls`, it lists **all** the shares from an account, regardless whether they are synced locally (see `nec ls -h`). Therefore the `-r` doesn't change anything and I should probably disallow `-r` when path is empty to hopefully reduce some confusion.

Anyway, I think the error message could be improved.

**Comment by muralikodali** [comment]
yes, this is working as intended with synced files (via nextcloud desktop client).

it will be more useful, if one can upload and share the link in one go.

**Comment by gnojus** [comment]
I agree it could be useful to upload.
However, I'm not sure if this should be done.

Right now, for me the main appeal of `nec` is that it's very simple, zero configuration and relatively harmless. Uploading would probably discard all of these.

Uploading is quite complex, and a lot questions needs to be answered. Where to upload? How to name it? Which account to pick if there are multiple? This would probably require additional configuration.

What to do with failed transfers, symlinks, etc? Unsharing would probably require deletion, and that is also easy to get wrong and loose important files.

So for now, my recommendation would be as written in updated README:
> <...> if you want to share a file that is not synced, you may want to move/copy it to a folder that is synchronized and share it from there. The upload will be performed by the desktop client.

The updated version also contains a better error message.
